/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package jackpackage;

/**
 *
 * @author Renzo
 */
public class VM_GUI extends javax.swing.JFrame {

    /**
     * Creates new form VM_GUI
     */
    public VM_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        CreateMenuGUI = new javax.swing.JFrame();
        CreateVendingMachinePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ConfirmSelection = new javax.swing.JButton();
        TestVendingMachinePanel = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonConfirm = new javax.swing.JButton();
        jTextAreaPane = new javax.swing.JScrollPane();
        jTextAreaConsole = new javax.swing.JTextArea();
        jInputTextField = new javax.swing.JTextField();
        jButton0 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        ItemRack = new javax.swing.JScrollPane();
        ItemPanel = new javax.swing.JPanel();
        ItemPic_2 = new javax.swing.JLabel();
        ItemPic1 = new javax.swing.JLabel();
        ItemPic3 = new javax.swing.JLabel();
        ItemName0 = new javax.swing.JLabel();
        ItemName1 = new javax.swing.JLabel();
        ItemName2 = new javax.swing.JLabel();
        ItemPic4 = new javax.swing.JLabel();
        ItemName3 = new javax.swing.JLabel();
        ItemPic5 = new javax.swing.JLabel();
        ItemName4 = new javax.swing.JLabel();
        ItemPic6 = new javax.swing.JLabel();
        ItemName5 = new javax.swing.JLabel();
        ItemPic7 = new javax.swing.JLabel();
        ItemName6 = new javax.swing.JLabel();
        ItemPic8 = new javax.swing.JLabel();
        ItemName7 = new javax.swing.JLabel();
        ItemPic9 = new javax.swing.JLabel();
        ItemName8 = new javax.swing.JLabel();
        ItemName9 = new javax.swing.JLabel();
        ItemPic10 = new javax.swing.JLabel();
        ItemName10 = new javax.swing.JLabel();
        ItemPic11 = new javax.swing.JLabel();
        ItemName11 = new javax.swing.JLabel();
        ItemPic12 = new javax.swing.JLabel();
        ItemName12 = new javax.swing.JLabel();
        ItemPic13 = new javax.swing.JLabel();
        ItemName13 = new javax.swing.JLabel();
        ItemPic14 = new javax.swing.JLabel();
        ItemName14 = new javax.swing.JLabel();
        ItemPic15 = new javax.swing.JLabel();
        ItemName15 = new javax.swing.JLabel();
        ItemPic16 = new javax.swing.JLabel();
        ItemName16 = new javax.swing.JLabel();
        ItemPic17 = new javax.swing.JLabel();
        ItemName17 = new javax.swing.JLabel();
        ItemPic18 = new javax.swing.JLabel();
        ItemName18 = new javax.swing.JLabel();
        ItemPic19 = new javax.swing.JLabel();
        ItemName19 = new javax.swing.JLabel();
        ItemPic20 = new javax.swing.JLabel();
        ItemName20 = new javax.swing.JLabel();
        ItemPic21 = new javax.swing.JLabel();
        ItemName21 = new javax.swing.JLabel();
        ItemPic22 = new javax.swing.JLabel();
        ItemName22 = new javax.swing.JLabel();
        ItemPic23 = new javax.swing.JLabel();
        ItemName23 = new javax.swing.JLabel();
        ItemPic24 = new javax.swing.JLabel();
        ItemName24 = new javax.swing.JLabel();
        ItemPic25 = new javax.swing.JLabel();
        ItemName25 = new javax.swing.JLabel();
        ItemPic26 = new javax.swing.JLabel();
        ItemName26 = new javax.swing.JLabel();
        ItemPic27 = new javax.swing.JLabel();
        ItemName27 = new javax.swing.JLabel();
        ItemPic28 = new javax.swing.JLabel();
        ItemName28 = new javax.swing.JLabel();
        ItemPic29 = new javax.swing.JLabel();
        ItemName29 = new javax.swing.JLabel();
        ItemPic30 = new javax.swing.JLabel();
        jVMName = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jComboMenu = new javax.swing.JMenu();
        jMenuCreate = new javax.swing.JMenu();
        CreateMenu = new javax.swing.JMenuItem();

        CreateMenuGUI.setMinimumSize(new java.awt.Dimension(411, 300));

        CreateVendingMachinePanel.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel1.setText("This is Jack YOUVE BEEN JACKED");

        ConfirmSelection.setText("Confirm");
        ConfirmSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConfirmSelectionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout CreateVendingMachinePanelLayout = new javax.swing.GroupLayout(CreateVendingMachinePanel);
        CreateVendingMachinePanel.setLayout(CreateVendingMachinePanelLayout);
        CreateVendingMachinePanelLayout.setHorizontalGroup(
            CreateVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CreateVendingMachinePanelLayout.createSequentialGroup()
                .addGroup(CreateVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CreateVendingMachinePanelLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(ConfirmSelection))
                    .addGroup(CreateVendingMachinePanelLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(64, Short.MAX_VALUE))
        );
        CreateVendingMachinePanelLayout.setVerticalGroup(
            CreateVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CreateVendingMachinePanelLayout.createSequentialGroup()
                .addContainerGap(37, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ConfirmSelection)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout CreateMenuGUILayout = new javax.swing.GroupLayout(CreateMenuGUI.getContentPane());
        CreateMenuGUI.getContentPane().setLayout(CreateMenuGUILayout);
        CreateMenuGUILayout.setHorizontalGroup(
            CreateMenuGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateVendingMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );
        CreateMenuGUILayout.setVerticalGroup(
            CreateMenuGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CreateVendingMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));

        TestVendingMachinePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton6.setText("6");
        jButton6.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton6.setIconTextGap(6);
        jButton6.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("7");
        jButton7.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton7.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("8");
        jButton8.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton8.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("9");
        jButton9.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton9.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButtonClear.setText("C");
        jButtonClear.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonClear.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonClear.setPreferredSize(new java.awt.Dimension(37, 20));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonConfirm.setText("✓");
        jButtonConfirm.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButtonConfirm.setPreferredSize(new java.awt.Dimension(37, 20));
        jButtonConfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmActionPerformed(evt);
            }
        });

        jTextAreaConsole.setColumns(20);
        jTextAreaConsole.setRows(5);
        jTextAreaConsole.setText("jTextPanel");
        jTextAreaPane.setViewportView(jTextAreaConsole);

        jInputTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jInputTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInputTextFieldActionPerformed(evt);
            }
        });

        jButton0.setText("0");
        jButton0.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton0.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton0ActionPerformed(evt);
            }
        });

        jButton1.setText("1");
        jButton1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton1.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("2");
        jButton2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton2.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("3");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("4");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("5");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton5.setPreferredSize(new java.awt.Dimension(37, 20));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        ItemRack.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        ItemRack.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        ItemRack.setViewportBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ItemRack.setHorizontalScrollBar(null);

        ItemPic_2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic_2.setText("ItemPic2");
        ItemPic_2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic_2.setFocusable(false);

        ItemPic1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic1.setText("ItemPic1");
        ItemPic1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic1.setFocusable(false);

        ItemPic3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic3.setText("ItemPic3");
        ItemPic3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic3.setFocusable(false);

        ItemName0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName0.setText("ItemName0");

        ItemName1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName1.setText("ItemName1");

        ItemName2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName2.setText("ItemName2");

        ItemPic4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic4.setText("ItemPic4");
        ItemPic4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic4.setFocusable(false);

        ItemName3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName3.setText("ItemName3");

        ItemPic5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic5.setText("ItemPic5");
        ItemPic5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic5.setFocusable(false);

        ItemName4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName4.setText("ItemName4");

        ItemPic6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic6.setText("ItemPic6");
        ItemPic6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic6.setFocusable(false);

        ItemName5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName5.setText("ItemName5");

        ItemPic7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic7.setText("ItemPic7");
        ItemPic7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic7.setFocusable(false);

        ItemName6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName6.setText("ItemName6");

        ItemPic8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic8.setText("ItemPic8");
        ItemPic8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic8.setFocusable(false);

        ItemName7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName7.setText("ItemName7");

        ItemPic9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic9.setText("ItemPic9");
        ItemPic9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic9.setFocusable(false);

        ItemName8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName8.setText("ItemName8");

        ItemName9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName9.setText("ItemName9");

        ItemPic10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic10.setText("ItemPic10");
        ItemPic10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic10.setFocusable(false);

        ItemName10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName10.setText("ItemName10");

        ItemPic11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic11.setText("ItemPic11");
        ItemPic11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic11.setFocusable(false);

        ItemName11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName11.setText("ItemName11");

        ItemPic12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic12.setText("ItemPic12");
        ItemPic12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic12.setFocusable(false);

        ItemName12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName12.setText("ItemName12");

        ItemPic13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic13.setText("ItemPic13");
        ItemPic13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic13.setFocusable(false);

        ItemName13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName13.setText("ItemName13");

        ItemPic14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic14.setText("ItemPic14");
        ItemPic14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic14.setFocusable(false);

        ItemName14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName14.setText("ItemName14");

        ItemPic15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic15.setText("ItemPic15");
        ItemPic15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic15.setFocusable(false);

        ItemName15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName15.setText("ItemName15");

        ItemPic16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic16.setText("ItemPic16");
        ItemPic16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic16.setFocusable(false);

        ItemName16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName16.setText("ItemName16");

        ItemPic17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic17.setText("ItemPic17");
        ItemPic17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic17.setFocusable(false);

        ItemName17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName17.setText("ItemName17");

        ItemPic18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic18.setText("ItemPic18");
        ItemPic18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic18.setFocusable(false);

        ItemName18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName18.setText("ItemName18");

        ItemPic19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic19.setText("ItemPic19");
        ItemPic19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic19.setFocusable(false);

        ItemName19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName19.setText("ItemName19");

        ItemPic20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic20.setFocusable(false);

        ItemName20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName20.setText("ItemName20");

        ItemPic21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic21.setFocusable(false);

        ItemName21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName21.setText("ItemName21");

        ItemPic22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic22.setFocusable(false);

        ItemName22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName22.setText("ItemName22");

        ItemPic23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic23.setFocusable(false);

        ItemName23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName23.setText("ItemName23");

        ItemPic24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic24.setFocusable(false);

        ItemName24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName24.setText("ItemName24");

        ItemPic25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic25.setFocusable(false);

        ItemName25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName25.setText("ItemName25");

        ItemPic26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic26.setFocusable(false);

        ItemName26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName26.setText("ItemName26");

        ItemPic27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic27.setFocusable(false);

        ItemName27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName27.setText("ItemName27");

        ItemPic28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic28.setFocusable(false);

        ItemName28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName28.setText("ItemName28");

        ItemPic29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic29.setFocusable(false);

        ItemName29.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemName29.setText("ItemName29");

        ItemPic30.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ItemPic30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ItemPic30.setFocusable(false);

        javax.swing.GroupLayout ItemPanelLayout = new javax.swing.GroupLayout(ItemPanel);
        ItemPanel.setLayout(ItemPanelLayout);
        ItemPanelLayout.setHorizontalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ItemPic13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemName12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPic19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemName18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPic25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemName24, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName13, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName15, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic18, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName17, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName19, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName20, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName21, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName22, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic24, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic26, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName25, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic27, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName26, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic28, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName27, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic29, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName28, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ItemPic30, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemName29, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemName6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemPic7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemPic8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemName7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemPic9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemName8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ItemPic10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemName9, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ItemName10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ItemName11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(ItemPic11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ItemPic12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemName0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemPic1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemPic_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemName1, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemPic3, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                            .addComponent(ItemName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemName3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemPic5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemName4, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ItemPic6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ItemName5, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ItemPanelLayout.setVerticalGroup(
            ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ItemPanelLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ItemPic_2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemPic1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemPic3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ItemName0)
                                    .addComponent(ItemName1)
                                    .addComponent(ItemName2)))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ItemPic5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemPic4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ItemPic6, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ItemName3)
                                    .addComponent(ItemName4)
                                    .addComponent(ItemName5))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemPic8, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPic7, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPic9, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemName6)
                            .addComponent(ItemName7)
                            .addComponent(ItemName8)))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemPic10, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPic11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemPic12, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ItemName10)
                            .addComponent(ItemName11)
                            .addComponent(ItemName9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic13, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName12))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName13))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic15, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName14))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic16, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName15))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic17, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName16))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic18, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addComponent(ItemPic19, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemName18))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addComponent(ItemPic20, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemName19))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addComponent(ItemPic21, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemName20)))
                        .addGroup(ItemPanelLayout.createSequentialGroup()
                            .addComponent(ItemPic22, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ItemName21)))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic23, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName22))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic24, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName23)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(ItemPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addComponent(ItemPic25, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemName24))
                            .addGroup(ItemPanelLayout.createSequentialGroup()
                                .addComponent(ItemPic26, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ItemName25)))
                        .addGroup(ItemPanelLayout.createSequentialGroup()
                            .addComponent(ItemPic27, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ItemName26)))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic28, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName27))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic29, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName28))
                    .addGroup(ItemPanelLayout.createSequentialGroup()
                        .addComponent(ItemPic30, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemName29)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        ItemRack.setViewportView(ItemPanel);

        jVMName.setText("jVMName");

        javax.swing.GroupLayout TestVendingMachinePanelLayout = new javax.swing.GroupLayout(TestVendingMachinePanel);
        TestVendingMachinePanel.setLayout(TestVendingMachinePanelLayout);
        TestVendingMachinePanelLayout.setHorizontalGroup(
            TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                        .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jVMName, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ItemRack, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                        .addComponent(jTextAreaPane)
                        .addGap(18, 18, 18)
                        .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                                    .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42))))
        );
        TestVendingMachinePanelLayout.setVerticalGroup(
            TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jVMName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TestVendingMachinePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ItemRack, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextAreaPane, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(42, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TestVendingMachinePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jInputTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(4, 4, 4)
                        .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(TestVendingMachinePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonConfirm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(71, 71, 71))))
        );

        jComboMenu.setText("Create ");

        jMenuCreate.setText("New Vending Machine");
        jMenuCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuCreateActionPerformed(evt);
            }
        });
        jComboMenu.add(jMenuCreate);

        CreateMenu.setText("jMenuItem1");
        CreateMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateMenuActionPerformed(evt);
            }
        });
        jComboMenu.add(CreateMenu);

        jMenuBar1.add(jComboMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TestVendingMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TestVendingMachinePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void jMenuCreateActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CreateMenuGUI.setVisible(!TestVendingMachinePanel.isVisible());
        //TestVendingMachinePanel.setVisible(!CreateMenuGUI.isVisible());
    }                                           

    private void jInputTextFieldActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    private void jButton0ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         jButtonActionPerformed(evt, "0");
    }                                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "1");
    }                                        

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "2");// TODO add your handling code here:
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "3");
    }                                        

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "4");
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "5");
    }                                        

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "6");
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "7");
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "8");
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jButtonActionPerformed(evt, "9");
    }                                        

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {                                             
        jInputTextField.setText("");
    }                                            

    private void jButtonConfirmActionPerformed(java.awt.event.ActionEvent evt) {                                               
        String string = jInputTextField.getText();
        jInputTextField.setText("");
        jTextAreaConsole.setText(string);
    }                                              

    private void CreateMenuActionPerformed(java.awt.event.ActionEvent evt) {                                           
        CreateMenuGUI.setVisible(true);
        //TestVendingMachinePanel.setVisible(false);
        //TestVendingMachinePanel.setVisible(!CreateMenuGUI.isVisible());
    }                                          

    private void ConfirmSelectionActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        CreateMenuGUI.setVisible(false);
        jInputTextField.setText("mrjack");
    }                                                

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt, String number) {
        String currentText = jInputTextField.getText();
        jInputTextField.setText(currentText + number);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VM_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton ConfirmSelection;
    private javax.swing.JMenuItem CreateMenu;
    private javax.swing.JFrame CreateMenuGUI;
    private javax.swing.JPanel CreateVendingMachinePanel;
    private javax.swing.JLabel ItemName0;
    private javax.swing.JLabel ItemName1;
    private javax.swing.JLabel ItemName10;
    private javax.swing.JLabel ItemName11;
    private javax.swing.JLabel ItemName12;
    private javax.swing.JLabel ItemName13;
    private javax.swing.JLabel ItemName14;
    private javax.swing.JLabel ItemName15;
    private javax.swing.JLabel ItemName16;
    private javax.swing.JLabel ItemName17;
    private javax.swing.JLabel ItemName18;
    private javax.swing.JLabel ItemName19;
    private javax.swing.JLabel ItemName2;
    private javax.swing.JLabel ItemName20;
    private javax.swing.JLabel ItemName21;
    private javax.swing.JLabel ItemName22;
    private javax.swing.JLabel ItemName23;
    private javax.swing.JLabel ItemName24;
    private javax.swing.JLabel ItemName25;
    private javax.swing.JLabel ItemName26;
    private javax.swing.JLabel ItemName27;
    private javax.swing.JLabel ItemName28;
    private javax.swing.JLabel ItemName29;
    private javax.swing.JLabel ItemName3;
    private javax.swing.JLabel ItemName4;
    private javax.swing.JLabel ItemName5;
    private javax.swing.JLabel ItemName6;
    private javax.swing.JLabel ItemName7;
    private javax.swing.JLabel ItemName8;
    private javax.swing.JLabel ItemName9;
    private javax.swing.JPanel ItemPanel;
    private javax.swing.JLabel ItemPic1;
    private javax.swing.JLabel ItemPic10;
    private javax.swing.JLabel ItemPic11;
    private javax.swing.JLabel ItemPic12;
    private javax.swing.JLabel ItemPic13;
    private javax.swing.JLabel ItemPic14;
    private javax.swing.JLabel ItemPic15;
    private javax.swing.JLabel ItemPic16;
    private javax.swing.JLabel ItemPic17;
    private javax.swing.JLabel ItemPic18;
    private javax.swing.JLabel ItemPic19;
    private javax.swing.JLabel ItemPic20;
    private javax.swing.JLabel ItemPic21;
    private javax.swing.JLabel ItemPic22;
    private javax.swing.JLabel ItemPic23;
    private javax.swing.JLabel ItemPic24;
    private javax.swing.JLabel ItemPic25;
    private javax.swing.JLabel ItemPic26;
    private javax.swing.JLabel ItemPic27;
    private javax.swing.JLabel ItemPic28;
    private javax.swing.JLabel ItemPic29;
    private javax.swing.JLabel ItemPic3;
    private javax.swing.JLabel ItemPic30;
    private javax.swing.JLabel ItemPic4;
    private javax.swing.JLabel ItemPic5;
    private javax.swing.JLabel ItemPic6;
    private javax.swing.JLabel ItemPic7;
    private javax.swing.JLabel ItemPic8;
    private javax.swing.JLabel ItemPic9;
    private javax.swing.JLabel ItemPic_2;
    private javax.swing.JScrollPane ItemRack;
    private javax.swing.JPanel TestVendingMachinePanel;
    private javax.swing.JButton jButton0;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonConfirm;
    private javax.swing.JMenu jComboMenu;
    private javax.swing.JTextField jInputTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCreate;
    private javax.swing.JTextArea jTextAreaConsole;
    private javax.swing.JScrollPane jTextAreaPane;
    private javax.swing.JLabel jVMName;
    // End of variables declaration                   
}